# MLOps with Agentic AI - Session 8: Complete CI/CD Pipeline
# Author: Amey Talkatkar
# Repository: https://github.com/ameytrainer/ml-forecast-system

# Hyperparameters and Configuration

preprocess:
  test_size: 0.2
  random_state: 42
  validation_size: 0.1

train:
  model_type: RandomForestRegressor
  n_estimators: 150
  max_depth: 40
  min_samples_split: 2
  min_samples_leaf: 1
  max_features: auto
  random_state: 42
  n_jobs: -1

evaluate:
  metrics:
    - mae
    - rmse
    - r2_score
    - mape
  
deployment:
  staging_threshold: 0.1  # Deploy to staging if MAE improves by 10%
  production_threshold: 0.05  # Deploy to prod if MAE improves by 5%
